parameters:
    mock_server.pid_file: "mock-server-pids"

services:
    mock_server.primer:
        class: MockServer\Server\Primer
        arguments: [%kernel.cache_dir%]

    mock_server.manager:
        class: MockServer\Manager\ServerManager
        arguments: [@mock_server.primer, %kernel.root_dir%, %kernel.cache_dir%, %mock_server.pid_file%]